pipeline {
    agent any
    
    stages {
        
        
        stage ('Terraform Apply') {
            steps {
                sh '''
                    make dev
                '''
            }
            
        }
    }
}