pipeline {
    agent any
    
    stages {
        
        
        stage ('Terraform Apply') {
            
            steps {
                
                sh 'echo hello'
            }
            
        }
    }
}