variable "env" {}
variable "od_ins" {}
variable "spot_ins" {}
variable "instance_type" {}
variable "component" {}
variable "port" {}
variable "is_internal" {}
variable "priority" {}
variable "APP_VERSION" {}